### ISSUE TITLE
[ENH] Inverse VMD 

### ISSUE THREAD

**Issue by shivaniarbat** [sktime/vmdpy#2] opened 2021-02-09 18:33 UTC
Hi @vrcarva. This is really helpful. Any leads on doing inverse VMD ?

**Comment by shivaniarbat** [comment] 2021-02-09 19:09
what variable hold value for residuals apart from _k_ signals output ?

**Comment by fkiraly** [comment] 2024-06-14 14:20
duplicate of https://github.com/sktime/sktime/issues/6605, see resolution there.

**Closed by fkiraly** 2024-06-14 14:20 UTC
